"""Generate bash completion script for the grim binary.

Usage:
    completion.py <src_dir>
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "command", "python"))
from command_docs import parse_source_files

FRAMEWORK_FLAGS = "--output --cache --filter --sort --select --limit --debug --help"
FRAMEWORK_PARAMS = {"output", "cache", "filter", "sort", "select", "limit", "debug", "help"}


def build_prefix_tree(commands):
    """Build map of prefix -> set of next words from command names."""
    prefixes = {}
    for name in commands:
        parts = name.split("_")
        for i in range(len(parts)):
            prefix = "_".join(parts[:i])
            prefixes.setdefault(prefix, set()).add(parts[i])
    return prefixes


def generate(commands):
    prefixes = build_prefix_tree(commands)

    out = []
    out.append("# Generated by: grim completion bash")
    out.append("# Add to ~/.bashrc: source <(grim completion bash)")
    out.append("")
    out.append("_grim_complete() {")
    out.append('    local cur="${COMP_WORDS[COMP_CWORD]}"')
    out.append('    local prev="${COMP_WORDS[COMP_CWORD-1]}"')
    out.append("")
    out.append('    if [[ "$prev" == "--output" ]]; then')
    out.append('        COMPREPLY=($(compgen -W "table json tsv md raw" -- "$cur"))')
    out.append("        return")
    out.append("    fi")
    out.append("")
    out.append('    local typed=("${COMP_WORDS[@]:1:$((COMP_CWORD-1))}")')
    out.append('    local prefix=""')
    out.append('    for word in "${typed[@]}"; do')
    out.append('        [[ "$word" == -* ]] && break')
    out.append('        prefix="${prefix:+${prefix}_}${word}"')
    out.append('    done')
    out.append("")
    out.append('    case "$prefix" in')

    # Full command matches — suggest flags
    for name in sorted(commands):
        cmd = commands[name]
        extra = " ".join(
            f'--{p["name"]}' for p in cmd["params"]
            if p["name"] not in FRAMEWORK_PARAMS
        )
        flags = f"{extra} {FRAMEWORK_FLAGS}".strip()
        out.append(f"        {name})")
        out.append(f'            COMPREPLY=($(compgen -W "{flags}" -- "$cur")) ;;')

    # Partial prefix matches — suggest next subcommand word
    for prefix in sorted(prefixes, key=lambda p: (-len(p), p)):
        if prefix in commands:
            continue
        words = " ".join(sorted(prefixes[prefix]))
        pattern = '""' if prefix == "" else prefix
        out.append(f"        {pattern})")
        out.append(f'            COMPREPLY=($(compgen -W "{words}" -- "$cur")) ;;')

    out.append("    esac")
    out.append("}")
    out.append("")
    out.append("complete -F _grim_complete grim")

    return "\n".join(out)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("src_dir")
    args = parser.parse_args()
    commands = parse_source_files(args.src_dir)
    print(generate(commands))
