"""Generate shell completion scripts for the grim binary.

Usage:
    completion.py <src_dir> --shell bash|zsh
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "command", "python"))
from command_docs import parse_source_files

FRAMEWORK_FLAGS = "--output --cache --filter --sort --select --limit --debug --help"
FRAMEWORK_PARAMS = {"output", "cache", "filter", "sort", "select", "limit", "debug", "help"}

_BASH_HEADER = """\
# Generated by: grim completion bash
# Add to ~/.bashrc: source <(grim completion bash)

_grim_complete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [[ "$prev" == "--output" ]]; then
        COMPREPLY=($(compgen -W "table json tsv md raw" -- "$cur"))
        return
    fi

    local typed=("${COMP_WORDS[@]:1:$((COMP_CWORD-1))}")
    local prefix=""
    for word in "${typed[@]}"; do
        [[ "$word" == -* ]] && break
        prefix="${prefix:+${prefix}_}${word}"
    done

    case "$prefix" in"""

_BASH_FOOTER = """\
    esac
}

complete -F _grim_complete grim"""

_ZSH_HEADER = """\
#compdef grim

# Generated by: grim completion zsh
# Add to ~/.zshrc: source <(grim completion zsh)

_grim() {
    local cur="${words[CURRENT]}"
    local prev="${words[CURRENT-1]}"

    if [[ "$prev" == "--output" ]]; then
        compadd table json tsv md raw
        return
    fi

    local -a cmd_words=()
    local word
    for word in "${words[@]:1:$((CURRENT-2))}"; do
        [[ "$word" == --* ]] && break
        cmd_words+=("$word")
    done
    local prefix="${(j:_:)cmd_words}"

    local in_flags=0
    [[ "$cur" == -* ]] && in_flags=1
    if (( !in_flags )); then
        for word in "${words[@]:1:$((CURRENT-1))}"; do
            [[ "$word" == --* ]] && in_flags=1 && break
        done
    fi

    case "$prefix" in"""

_ZSH_MIDDLE = """\
    esac

    (( in_flags )) && return

    case "$prefix" in"""

_ZSH_FOOTER = """\
    esac
}

_grim "$@\""""


def build_prefix_tree(commands):
    """Build map of prefix -> set of next words from command names."""
    prefixes = {}
    for name in commands:
        parts = name.split("_")
        for i in range(len(parts)):
            prefix = "_".join(parts[:i])
            prefixes.setdefault(prefix, set()).add(parts[i])
    return prefixes


def command_flags(cmd):
    extra = " ".join(
        f'--{p["name"]}' for p in cmd["params"]
        if p["name"] not in FRAMEWORK_PARAMS
    )
    return f"{extra} {FRAMEWORK_FLAGS}".strip()


def generate_bash(commands):
    prefixes = build_prefix_tree(commands)

    cases = []
    for name in sorted(commands):
        flags = command_flags(commands[name])
        cases.append(f'        {name})\n            COMPREPLY=($(compgen -W "{flags}" -- "$cur")) ;;')

    for prefix in sorted(prefixes, key=lambda p: (-len(p), p)):
        if prefix in commands:
            continue
        words = " ".join(sorted(prefixes[prefix]))
        pattern = '""' if prefix == "" else prefix
        cases.append(f'        {pattern})\n            COMPREPLY=($(compgen -W "{words}" -- "$cur")) ;;')

    return "\n".join([_BASH_HEADER, "\n".join(cases), _BASH_FOOTER])


def generate_zsh(commands):
    prefixes = build_prefix_tree(commands)

    flag_cases = []
    for name in sorted(commands):
        flags = command_flags(commands[name])
        flag_cases.append(f"        {name})\n            compadd -- {flags} ; return ;;")

    prefix_cases = []
    for prefix in sorted(prefixes, key=lambda p: (-len(p), p)):
        if prefix in commands:
            continue
        words = " ".join(sorted(prefixes[prefix]))
        pattern = '""' if prefix == "" else prefix
        prefix_cases.append(f"        {pattern})\n            compadd -- {words} ; return ;;")

    return "\n".join([
        _ZSH_HEADER,
        "\n".join(flag_cases),
        _ZSH_MIDDLE,
        "\n".join(prefix_cases),
        _ZSH_FOOTER,
    ])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("src_dir")
    parser.add_argument("--shell", default="bash", choices=["bash", "zsh"])
    args = parser.parse_args()
    commands = parse_source_files(args.src_dir)
    if args.shell == "zsh":
        print(generate_zsh(commands))
    else:
        print(generate_bash(commands))
