# Completion scripts for the rig binary

completion_bash() {
    _description "Generate bash completion script for the rig binary"
    _param_parse "$@" || return 1
    cat << 'COMPLETION'
# Generated by: rig completion bash
# Add to ~/.bashrc: source <(rig completion bash)

_rig_complete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    local typed=("${COMP_WORDS[@]:1:$((COMP_CWORD-1))}")
    local prefix=""
    for word in "${typed[@]}"; do
        [[ "$word" == -* ]] && break
        prefix="${prefix:+${prefix}_}${word}"
    done

    COMPREPLY=($(compgen -W "$(rig __complete "$prefix" "$prev" "$cur" 2>/dev/null)" -- "$cur"))
}

complete -F _rig_complete rig
COMPLETION
}

completion_zsh() {
    _description "Generate zsh completion script for the rig binary"
    _param_parse "$@" || return 1
    cat << 'COMPLETION'
#compdef rig

# Generated by: rig completion zsh
# Add to ~/.zshrc: source <(rig completion zsh)

_tome() {
    local cur="${words[CURRENT]}"
    local prev="${words[CURRENT-1]}"

    local -a cmd_words=()
    local word
    for word in "${words[@]:1:$((CURRENT-2))}"; do
        [[ "$word" == --* ]] && break
        cmd_words+=("$word")
    done
    local prefix="${(j:_:)cmd_words}"

    local -a results
    results=($(rig __complete "$prefix" "$prev" "$cur" 2>/dev/null))
    compadd -- "${results[@]}"
}

_tome "$@"
COMPLETION
}

_complete_params "completion_bash"
_complete_params "completion_zsh"
