# Completion scripts for the tome binary

completion_bash() {
    _param_parse "$@" || return 1
    cat << 'COMPLETION'
# Generated by: tome completion bash
# Add to ~/.bashrc: source <(tome completion bash)

_tome_complete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    local typed=("${COMP_WORDS[@]:1:$((COMP_CWORD-1))}")
    local prefix=""
    for word in "${typed[@]}"; do
        [[ "$word" == -* ]] && break
        prefix="${prefix:+${prefix}_}${word}"
    done

    COMPREPLY=($(compgen -W "$(tome __complete "$prefix" "$prev" "$cur" 2>/dev/null)" -- "$cur"))
}

complete -F _tome_complete tome
COMPLETION
}

completion_zsh() {
    _param_parse "$@" || return 1
    cat << 'COMPLETION'
#compdef tome

# Generated by: tome completion zsh
# Add to ~/.zshrc: source <(tome completion zsh)

_tome() {
    local cur="${words[CURRENT]}"
    local prev="${words[CURRENT-1]}"

    local -a cmd_words=()
    local word
    for word in "${words[@]:1:$((CURRENT-2))}"; do
        [[ "$word" == --* ]] && break
        cmd_words+=("$word")
    done
    local prefix="${(j:_:)cmd_words}"

    local -a results
    results=($(tome __complete "$prefix" "$prev" "$cur" 2>/dev/null))
    compadd -- "${results[@]}"
}

_tome "$@"
COMPLETION
}

_complete_params "completion_bash" "Generate bash completion script for the tome binary"
_complete_params "completion_zsh" "Generate zsh completion script for the tome binary"
