# Completion scripts for the jig binary

completion_bash() {
    _description "Generate bash completion script for the jig binary"
    _param_parse "$@" || return 1
    cat << 'COMPLETION'
# Generated by: jig completion bash
# Add to ~/.bashrc: source <(jig completion bash)

_jig_complete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    local typed=("${COMP_WORDS[@]:1:$((COMP_CWORD-1))}")
    local prefix=""
    for word in "${typed[@]}"; do
        [[ "$word" == -* ]] && break
        prefix="${prefix:+${prefix}_}${word}"
    done

    local raw
    raw="$(jig __complete "$prefix" "$prev" "$cur" "${typed[@]}" 2>/dev/null)"
    if [[ "$raw" == "__path_dir" ]]; then
        compopt -o nospace
        COMPREPLY=($(compgen -d -- ${cur/#\~/$HOME} | sed "s|^$HOME|~|"))
    elif [[ "$raw" == "__path_file" ]]; then
        compopt -o nospace
        COMPREPLY=($(compgen -f -- ${cur/#\~/$HOME} | sed "s|^$HOME|~|"))
    else
        COMPREPLY=($(compgen -W "$raw" -- "$cur"))
    fi
}

complete -F _jig_complete jig
COMPLETION

    # Include shell.bash from installed packs
    local f
    for f in "$HOME/.jig/pack"/*/shell.bash; do
        [[ -f "$f" ]] || continue
        echo
        echo "# $(basename "$(dirname "$f")")"
        cat "$f"
    done
}

completion_zsh() {
    _description "Generate zsh completion script for the jig binary"
    _param_parse "$@" || return 1
    cat << 'COMPLETION'
# Generated by: jig completion zsh
# Add to ~/.zshrc: source <(jig completion zsh)

_jig() {
    local cur="${words[CURRENT]}"
    local prev="${words[CURRENT-1]}"

    local -a cmd_words=()
    local word
    local n=$(( CURRENT > 2 ? CURRENT - 2 : 0 ))
    for word in "${words[@]:1:$n}"; do
        [[ "$word" == --* ]] && break
        cmd_words+=("$word")
    done
    local prefix="${(j:_:)cmd_words}"

    local -a typed=("${words[@]:1:$n}")
    local raw
    raw="$(jig __complete "$prefix" "$prev" "$cur" "${typed[@]}" 2>/dev/null)"
    if [[ "$raw" == "__path_dir" ]]; then
        local expanded="${cur/#\~/$HOME}"
        local -a results=("${(@f)$(compgen -d -- "$expanded" | sed "s|^$HOME|~|")}")
        compadd -f -- "${results[@]}"
    elif [[ "$raw" == "__path_file" ]]; then
        local expanded="${cur/#\~/$HOME}"
        local -a results=("${(@f)$(compgen -f -- "$expanded" | sed "s|^$HOME|~|")}")
        compadd -f -- "${results[@]}"
    else
        local -a results=("${(@f)$raw}")
        compadd -- "${results[@]}"
    fi
}

compdef _jig jig
COMPLETION

    # Include shell.zsh from installed packs
    local f
    for f in "$HOME/.jig/pack"/*/shell.zsh; do
        [[ -f "$f" ]] || continue
        echo
        echo "# $(basename "$(dirname "$f")")"
        cat "$f"
    done
}

_complete_params "completion_bash"
_complete_params "completion_zsh"
